spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/mydb_dev
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        tool:
          schema: DEBUG