spring:
  config:
    import: optional:file:.env[.properties]

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: ${DATABASE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true  # SQL 줄바꿈/들여쓰기
        highlight_sql: true # ANSI 컬러로 하이라이트 (Hibernate 6+)

  # OAuth2 소셜로그인 설정
  security:
    oauth2:
      client:
        registration:
          kakao:  # 카카오 로그인 설정
            client-id: ${KAKAO_CLIENT_ID}  # 환경변수로 설정 (보안상 중요!)
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: ${KAKAO_REDIRECT_URI}
            client-name: Kakao
        provider:
          kakao:  # 카카오 OAuth2 제공자 설정
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id  # 카카오에서 사용자 식별자로 사용할 속성
  sql:
    init:
      mode: never
      encoding: UTF-8

# JWT 토큰 설정
jwt:
  secret: ${JWT_SECRET}
  # Access Token: 짧은 만료시간 (보안 강화)
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}    # 1시간 (1 * 60 * 60 * 1000)
  # Refresh Token: 긴 만료시간 (사용자 편의성)
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

app:
  frontend-url: ${FRONTEND_URL}

cors:
  allowed-origins:
    http://localhost:5173,
    http://localhost:8080,
    https://devseed.store


logging:
  level:
    org:
      springframework.security: DEBUG