name: ♻️ refactor
description: 기능 변화 없이 코드 구조 또는 성능을 개선하는 작업입니다.
title: "[♻️ refactor] "
labels: ["♻️ refactor"]
body:
  - type: textarea
    id: refactor-summary
    attributes:
      label: ✨ 어떤 리팩토링인가요?
      description: 어떤 코드를 리팩토링하려는지 요약해 주세요.
      placeholder: ex) AuthService의 로그인 흐름을 분리하여 책임을 명확히 합니다.
    validations:
      required: true

  - type: textarea
    id: refactor-reason
    attributes:
      label: 📌 리팩토링 이유
      description: 해당 리팩토링이 왜 필요한지 작성해 주세요.
      placeholder: ex) 중복된 로직이 많고 테스트하기 어려운 구조입니다.
    validations:
      required: true

  - type: textarea
    id: memo
    attributes:
      label: 🗒️ 메모
      description: 공유하고 싶은 내용이나 리뷰 요청, 논의 사항이 있다면 자유롭게 적어 주세요.
      placeholder: ex) Service → UseCase 구조 변경에 대해 논의가 필요합니다.